export { default as useAppContext } from './hooks/customHooks';
export { default as tkdt } from './fakeData/tkdt';
export { default as tksp } from './fakeData/tksp';
export { default as qlsp } from './fakeData/qlsp';
export { default as qlnd } from './fakeData/qlnd';
export { default as qlph } from './fakeData/qlph';
export { default as indexTable } from './Pageindex';
export * as handleLaguage from './handleLanguage';
export * as moneys from './format/Money';
export * as numbers from './format/Number';
export * as texts from './format/Text';
export * as dates from './format/Date';
export * as api from './axios/axiosInstance';
export * as store from './localStore';
